# -*- coding: utf-8 -*-
"""Linear_reg_multiple_var.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uXD3_s7pbyft8-yyWLvINvkoYaDQ48f-
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn import linear_model

df=pd.read_csv("/content/drive/MyDrive/ML Projects/homeprices_multiple_var.csv")
df

#Data Pre Processing
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

# Replace NaN value with median
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

# price = m1*area +m2*bedrooms + m3*area + b
reg.coef_
#below are values of m1,m2,m3

reg.intercept_

reg.predict([[3000,3,25]])

#Recheck
112.06244194*3000 + 23388.88007794*3 - 3231.71790863*25 + 221323.00186540396
#working 👌

reg.predict([[2500,4,5]])